### ISSUE TITLE
Implement assembleStorage for SparseMatrix_COO

### ISSUE THREAD

**Issue by bkochuna** [bkochuna/ners570f22-SpMV#10]
## Background
Our design uses an intermediate formate (map) for building up coefficients in the matrix, and part of the stated funcitonal requirments is that we convert that format to COO to be able to do matVecs and retrieve that format.

## Tasks
- [ ] Implement the funcitonal routine
- [ ] Write the unit test for that routine
- [ ] Document that routine

## Definition of Done
The routine is implemented, passing the test, and the work has been reviewed by at least one student.
