### ISSUE TITLE
Unassemble Storage for DEN

### ISSUE THREAD

**Issue by SoumiKDaS1701** [bkochuna/ners570f22-SpMV#17]
## Background
This should unassemble the storage in Dense matrix format

## Tasks

- [ ] Implement unassemble routine
- [ ] Perform unit tests to verify the code

## Definition of Done

- [ ] The code compiles correctly
- [ ] Passes all the unit tests

**Comment by A-CGray** [comment]
Completed in #86
