### ISSUE TITLE
Destructor for DEN

### ISSUE THREAD

**Issue by SoumiKDaS1701** [bkochuna/ners570f22-SpMV#19]
## Background
This was created to set up destructor in Dense matrix format

## Tasks

- [ ]  Implement destructor for DEN
- [ ]  Perform Unit testing to verify the code

## Definition of Done
- [ ]  The code compiles correctly
- [ ]  Passes all the unit tests

**Comment by A-CGray** [comment]
Completed in #86
