### ISSUE TITLE
assembleStorage for ELL

### ISSUE THREAD

**Issue by coltongraham99** [bkochuna/ners570f22-SpMV#27]
## Background
We require a function which takes the coefficient map and creates builds the underlying array structure for ELL

## Tasks
- [ ] Check for building state
- [ ] Create storage arrays for matrix
- [ ] Populate arrays from map
- [ ] Change state to assembled
- [ ] Write unit test for function
- [ ] Document function 

## Definition of Done

- [ ] Method is implemented
- [ ] Method passes unit tests
- [ ] Work has been reviewed by someone else

**Comment by bkochuna** [comment]
Same here. I believe this got assigned to a different student in Lab 07. (I could be wrong though)
