### ISSUE TITLE
Unassemble for JDS

### ISSUE THREAD

**Issue by coltongraham99** [bkochuna/ners570f22-SpMV#28]
## Background
We need to unassemble the data format for JDS so that it can be rebuilt with changed coefficients

## Tasks
- [ ] Check for assembled state
- [ ] Disassemble underlying JDS storage data 
- [ ] Add existing data to map structure
- [ ] Change state to building
- [ ] Write unit test for function
- [ ] Document function 

## Definition of Done

- [ ] Method is implemented
- [ ] Method passes unit tests
- [ ] Work has been reviewed by someone else

**Comment by bkochuna** [comment]
Hi Colton, I think this got assigned to a different student in lab last Friday.
