### ISSUE TITLE
Implement Overloaded DEN Constructor

### ISSUE THREAD

**Issue by tcoonsUM** [bkochuna/ners570f22-SpMV#40]
## Background
Overloaded constructor for the DEN matrix format. Called via:
`SparseMatrix_DEN<fp_type>* A_den = new SparseMatrix_DEN<fp_type>(m, n, a[][])`

## Tasks

- [x] Implement constructor function for DEN
- [x] Comment function/routine
- [x] Write a test for the constructor function
- [x] Add DBC checks in routine

## Definition of Done

- [x] Code has been implemented
- [x] Code has been tested
- [x] Code has been reviewed by >=1 student
- [x] Code is merged via a pull request

**Comment by bkochuna** [comment]
There's gonna be more to it than that!

You also have to write a test for the destructor, and comment your routine.
Please also consider adding DBC checks in your routine as a task.

Definition of done needs some work. The issue is closed when:
The code is implemented and tested.
The Code has been reviewed by at least one other student (this can be done during a pull request).
The code is merged. Via a pull request.

**Comment by tcoonsUM** [comment]
> There's gonna be more to it than that!
> 
> You also have to write a test for the destructor, and comment your routine. Please also consider adding DBC checks in your routine as a task.
> 
> Definition of done needs some work. The issue is closed when: The code is implemented and tested. The Code has been reviewed by at least one other student (this can be done during a pull request). The code is merged. Via a pull request.

Can you clarify what DBC checks are? (also thank you for the notes above)

**Comment by bkochuna** [comment]
DBC is design by contract. These are the `assert` statements that we used in lab.
