### ISSUE TITLE
Implement Overloaded JDS Constructor

### ISSUE THREAD

**Issue by tcoonsUM** [bkochuna/ners570f22-SpMV#41]
## Background
Constructor for the JDS matrix format, to allocate memory and define the variables of the JDS class structure. This is an overloaded constructor (a second constructor of a different form), with use like:

`SparseMatrix_JDS<fp_type>* A_coo = new SparseMatrix_JDS<fp_type>(m, n, perm[], jdiag[], col_ind[], jd_ptr[], val[])`

## Tasks

- [x] Implement constructor function for JDS
- [x] Comment function/routine
- [x] Write a test for the constructor function

## Definition of Done

- [x] Code has been implemented
- [x] Code has been tested
- [x] Code has been reviewed by >=1 student
- [x] Code is merged via a pull request

**Comment by dorukaks** [comment]
Do you want to `assembleStorage` as a part of #44 instead of this duplicate issue?

**Comment by bkochuna** [comment]
@dorukaks o these are not "duplicate issues" I used the wrong terminology in class. These are really extended/overloaded destructors on the subclasses.

**Comment by A-CGray** [comment]
This is a duplicate issue though, see #22

**Comment by tcoonsUM** [comment]
@bkochuna @A-CGray @dorukaks any qualms with me removing this issue and doing `assembleStorage` as a part of https://github.com/bkochuna/ners570f22-SpMV/pull/44 instead? Looks like no one has that task still

**Comment by bkochuna** [comment]
I think I may have misspoke in the lab for what I intended to call "duplicate constructors" I might've said "duplicate destructors".

In any case, the purpose was to implement an overloaded constructor so that the JDS Sparse matrix had a second way of constructing the object through an interface like:

SparseMatrix_JDS<fp_type>* A_coo = new SparseMatrix_JDS<fp_type>(m, n, perm[], jdiag[], col_ind[], jd_ptr[], val[])
So it skips the "building" state.

**Comment by bkochuna** [comment]
Need to update description.

**Comment by tcoonsUM** [comment]
> `perm[], jdiag[], col_ind[], jd_ptr[], val[])`

@bkochuna what is val[] in this case? I think the JDS format does not require more than 4 data structures (perm[], jdiag[], col_ind[], jd_ptr[]) so I will leave val[] out for now

**Comment by tcoonsUM** [comment]
Also @bkochuna there is no one assigned to the plain ol' constructor for the JDS format (which I would assume is a more common use case). Should I just do that instead?

**Comment by bkochuna** [comment]
> > `perm[], jdiag[], col_ind[], jd_ptr[], val[])`
> 
> @bkochuna what is val[] in this case? I think the JDS format does not require more than 4 data structures (perm[], jdiag[], col_ind[], jd_ptr[]) so I will leave val[] out for now

Yep. You're right, was thinking `val[]` was what `jdiag[]` was.

**Comment by bkochuna** [comment]
> Also @bkochuna there is no one assigned to the plain ol' constructor for the JDS format (which I would assume is a more common use case). Should I just do that instead?

Yeah, go ahead and implement this as well. The basic constructor should just reference the base classe's constructor.

**Comment by tcoonsUM** [comment]
Merged and reviewed.
