### ISSUE TITLE
Destructor for COO (duplicate) 

### ISSUE THREAD

**Issue by erinburrell** [bkochuna/ners570f22-SpMV#42]
## Background
Destructor for the COO matrix format, to destroy a COO matrix class instance and free memory after its use.

## Tasks

- [ ] Implement destructor function for COO
- [ ] Comment function/routine
- [ ] Write a test for the destructor function

## Definition of Done

- [ ] Code has been implemented
- [ ]  Code has been tested
- [ ] Code has been reviewed by at least one other student
- [ ] Code is merged via a pull request

**Comment by bkochuna** [comment]
I think I may have misspoke in the lab for what I intended to call "duplicate constructors" I might've said "duplicate destructors".

In any case, the purpose was to implement an overloaded constructor so that the COO Sparse matrix had a second way of constructing the object through an interface like:
```
SparseMatrix_COO<fp_type>* A_coo = new SparseMatrix_COO<fp_type>(m, n, i[], j[], val[])
```
So it skips the "building" state.
