### ISSUE TITLE
Unassemble for COO (duplicate) 

### ISSUE THREAD

**Issue by erinburrell** [bkochuna/ners570f22-SpMV#43]
## Background
Unassemble the storage in COO format. 

## Tasks

- [ ] Implement unassemble routine. 
- [ ] Comment function/routine.
- [ ] Write a test

## Definition of Done

- [ ]  Code has been implemented
- [ ] Code has been tested
- [ ] Code has been reviewed by at least one other student
- [ ] Code is merged via a pull request

**Comment by A-CGray** [comment]
Hey @erinburrell, nobody is currently assigned to do the `unassemble` method for JDS, perhaps you could do that instead of this duplicate?

**Comment by bkochuna** [comment]
We will make #7 the duplicate.

**Comment by erinburrell** [comment]
Code has been implemented and committed to branch issues_6_43_COO_unassemble_assemble. Testing has not been done yet

**Comment by erinburrell** [comment]
test code written
