### ISSUE TITLE
Implement Function to import data as matrix market format

### ISSUE THREAD

**Issue by coltongraham99** [bkochuna/ners570f22-SpMV#48]
## Background
The SpMV code ought to be able to allow the user to simply provide a filename to a function and have it perform the initialization and set the coefficient in the matrix

## Tasks
- [ ] Define function interface for importMatrix
- [ ] Write implementation to get matrix metadata and create matrix with it
- [ ] Write the reading of the data and setting of the coefficients
- [ ] Write units tests for importMatrix

## Definition of Done

- [ ] Function is capable of importing matrix market files
- [ ] Function passes unit tests for reading in format
