### ISSUE TITLE
Implemented automated formatting/linting for commits

### ISSUE THREAD

**Issue by bkochuna** [bkochuna/ners570f22-SpMV#57]
## Background
To facilitate developer effectiveness across large projects it is helpful to have some standardized formatting guidelines.

Requiring all your developers to know these guidelines explicitly and remember to follow them is time consuming and error prone.

Reformatting code to some style guide is a good task to be automated in the workflow.

There are several ways this can be done, but ideally, you want it to be done before a commit is executed. Additionally, you want the reformatting to not require any additional actions on the part of the developer, nor do you want it to pull in any major dependencies or require a complex setup on the part of a new developer, or when switching to a new machine for development.

## Tasks
- [ ] Identify appropriate mechanisms for scripting pre-commit reformatting
- [ ] Implement the pre-commit formatting
- [ ] (Optional) provide some capability to test this workflow.

## Definition of Done
The above tasks are completed, if possible this workflow feature is tested. Code is reviewed by an instructor.
