### ISSUE TITLE
Overload `setCoefficient`

### ISSUE THREAD

**Issue by sahilbhola14** [bkochuna/ners570f22-SpMV#65]
## Background
Current implementation sets the coefficient one at a time. Overloading will help assign multiple coefficient at once 

## Tasks
Overload `setCoefficient` such the method takes in pointers and thereby set coefficient for an array.

## Definition of Done
- [ ] `matVec` produces the correct result
- [ ] All tasks are complete
- [ ] Tests are working
- [ ] Code is reviewed and integrated with the production branch
